"""Marlin serial protocol string constants.

GENERATED by scripts/gen_constants.py -- do not edit by hand.
Run `just codegen` to regenerate. Source: Marlin latest-2.1.2.x @ 1cd56c4c.

Message literals are extracted from Marlin/src/core/language.h; structural
prefixes come from the serial emitters and are cited inline.
"""

MARLIN_REF = "latest-2.1.2.x"
MARLIN_SHA = "1cd56c4ccd483045eb5a92c99e3ad3b5ab1bea6d"

# --- message literals (core/language.h STR_*) ---
OK = 'ok'  # STR_OK
WAIT = 'wait'  # STR_WAIT
RESEND = 'Resend: '  # STR_RESEND
BUSY_PROCESSING = 'busy: processing'  # STR_BUSY_PROCESSING
BUSY_PAUSED_FOR_USER = 'busy: paused for user'  # STR_BUSY_PAUSED_FOR_USER
BUSY_PAUSED_FOR_INPUT = 'busy: paused for input'  # STR_BUSY_PAUSED_FOR_INPUT
ERR_KILLED = 'Printer halted. kill() called!'  # STR_ERR_KILLED
ERR_STOPPED = 'Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)'  # STR_ERR_STOPPED
ERR_CHECKSUM_MISMATCH = 'checksum mismatch, Last Line: '  # STR_ERR_CHECKSUM_MISMATCH
ERR_NO_CHECKSUM = 'No Checksum with line number, Last Line: '  # STR_ERR_NO_CHECKSUM
ERR_LINE_NO = 'Line Number is not Last Line Number+1, Last Line: '  # STR_ERR_LINE_NO
UNKNOWN_COMMAND = 'Unknown command: "'  # STR_UNKNOWN_COMMAND

# --- structural prefixes (serial emitters) ---
ECHO_PREFIX = 'echo:'  # core/serial.cpp serial_echo_start()
ERROR_PREFIX = 'Error:'  # core/serial.cpp serial_error_start()
ACTION_PREFIX = '//action:'  # feature/host_actions.cpp
CAP_PREFIX = 'Cap:'  # gcode/host/M115.cpp cap_line()
FIRMWARE_PREFIX = 'FIRMWARE_NAME:'  # gcode/host/M115.cpp
BUSY_PREFIX = 'busy:'  # shared head of STR_BUSY_* (core/language.h)
START = 'start'  # MarlinCore.cpp setup()

# --- fatal-state markers: a received line containing any of these means
# the controller has halted/stopped and the host must stop streaming ---
FATAL_MARKERS = (
    'Printer halted. kill() called!',  # STR_ERR_KILLED
    'Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)',  # STR_ERR_STOPPED
    '!! KILL caused by ',  # STR_KILL_PRE
    ', system stopped! Heater_ID: ',  # STR_STOPPED_HEATER
    'Thermal Runaway',  # STR_T_THERMAL_RUNAWAY
    'Heating failed',  # STR_T_HEATING_FAILED
    'MAXTEMP triggered',  # STR_T_MAXTEMP
    'MINTEMP triggered',  # STR_T_MINTEMP
)
