#!/usr/bin/env python3
"""Generate ``marlin_host/_constants.py`` from vendored Marlin source.

Run ``python scripts/fetch_marlin.py`` first (populates ``vendor/marlin/``).
This extracts the device->host **message literals** (``STR_*``) from
``language.h`` and emits a committed constants module. The library imports only
the committed module — never ``vendor/`` or ``_reference/``.

Structural prefixes (``echo:``, ``Error:`` …) are added by the serial emitters,
not ``language.h``; they are stable across versions and listed here with source
citations so the generated module is the single, regeneratable source of truth.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_VENDOR = _ROOT / "vendor" / "marlin"
_LANGUAGE_H = _VENDOR / "Marlin" / "src" / "core" / "language.h"
_OUT = _ROOT / "marlin_host" / "_constants.py"

# STR_* message macros we surface -> the Python constant name.
_WANTED = {
    "STR_OK": "OK",
    "STR_WAIT": "WAIT",
    "STR_RESEND": "RESEND",
    "STR_BUSY_PROCESSING": "BUSY_PROCESSING",
    "STR_BUSY_PAUSED_FOR_USER": "BUSY_PAUSED_FOR_USER",
    "STR_BUSY_PAUSED_FOR_INPUT": "BUSY_PAUSED_FOR_INPUT",
    "STR_ERR_KILLED": "ERR_KILLED",
    "STR_ERR_STOPPED": "ERR_STOPPED",
    "STR_ERR_CHECKSUM_MISMATCH": "ERR_CHECKSUM_MISMATCH",
    "STR_ERR_NO_CHECKSUM": "ERR_NO_CHECKSUM",
    "STR_ERR_LINE_NO": "ERR_LINE_NO",
    "STR_UNKNOWN_COMMAND": "UNKNOWN_COMMAND",
}

# Structural prefixes (constant, name) -> (literal, source citation). Not in
# language.h; added by the serial emitters. `BUSY_PREFIX` is the shared head of
# the STR_BUSY_* states; `START` is a bare echo in MarlinCore.cpp.
_STRUCTURAL = {
    "ECHO_PREFIX": ("echo:", "core/serial.cpp serial_echo_start()"),
    "ERROR_PREFIX": ("Error:", "core/serial.cpp serial_error_start()"),
    "ACTION_PREFIX": ("//action:", "feature/host_actions.cpp"),
    "CAP_PREFIX": ("Cap:", "gcode/host/M115.cpp cap_line()"),
    "FIRMWARE_PREFIX": ("FIRMWARE_NAME:", "gcode/host/M115.cpp"),
    "BUSY_PREFIX": ("busy:", "shared head of STR_BUSY_* (core/language.h)"),
    "START": ("start", "MarlinCore.cpp setup()"),
}

_DEFINE = re.compile(r'#define\s+(STR_\w+)\s+"((?:[^"\\]|\\.)*)"')


def _parse_literals(text: str) -> dict[str, str]:
    found: dict[str, str] = {}
    for match in _DEFINE.finditer(text):
        name = match.group(1)
        if name in _WANTED:
            # Decode C escapes (e.g. \" -> ").
            found[name] = match.group(2).encode().decode("unicode_escape")
    missing = sorted(set(_WANTED) - set(found))
    if missing:
        raise SystemExit(f"gen_constants: STR_* macros not found in language.h: {missing}")
    return found


def _render(literals: dict[str, str], ref: str, sha: str) -> str:
    lines = [
        '"""Marlin serial protocol string constants.',
        "",
        "GENERATED by scripts/gen_constants.py -- do not edit by hand.",
        f"Run `just codegen` to regenerate. Source: Marlin {ref} @ {sha[:8]}.",
        "",
        "Message literals are extracted from Marlin/src/core/language.h; structural",
        "prefixes come from the serial emitters and are cited inline.",
        '"""',
        "",
        f'MARLIN_REF = "{ref}"',
        f'MARLIN_SHA = "{sha}"',
        "",
        "# --- message literals (core/language.h STR_*) ---",
    ]
    for macro, const in _WANTED.items():
        lines.append(f"{const} = {literals[macro]!r}  # {macro}")
    lines += ["", "# --- structural prefixes (serial emitters) ---"]
    for const, (literal, citation) in _STRUCTURAL.items():
        lines.append(f"{const} = {literal!r}  # {citation}")
    return "\n".join(lines) + "\n"


def main() -> None:
    if not _LANGUAGE_H.exists():
        sys.exit(
            f"gen_constants: {_LANGUAGE_H} missing. Run `python scripts/fetch_marlin.py` first."
        )
    ref_file = (_VENDOR / "MARLIN_REF").read_text().split()
    ref, sha = ref_file[0], ref_file[1]
    literals = _parse_literals(_LANGUAGE_H.read_text(encoding="utf-8"))
    _OUT.write_text(_render(literals, ref, sha), encoding="utf-8")
    print(f"wrote {_OUT.relative_to(_ROOT)} from Marlin {ref} @ {sha[:8]}")


if __name__ == "__main__":
    main()
